fix(pyproject.toml): remove Hatchling build system
npm is not required here as the build happens in the Dockerfile as
separate and isolated build stage

I honestly don't know what this is for; I assume for local,
non-containerized development setups or it's remaining from times
when the project was not built with a Containerfile.

== Why was this changed?

To resolve error on uv sync:

   container # uv sync
   Resolved 322 packages in 2ms
     × Failed to build `open-webui @ file:///app`
     ├─▶ The build backend returned an error
     ╰─▶ Call to `hatchling.build.build_editable` failed (exit status: 1)

         [stderr]
         >>> Building Open Webui frontend
         Traceback (most recent call last):
           File "<string>", line 11, in <module>
           File "/root/.cache/uv/builds-v0/.tmpIFBcmT/lib/python3.11/site-packages/hatchling/build.py", line 83, in build_editable
             return os.path.basename(next(builder.build(directory=wheel_directory, versions=['editable'])))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           File "/root/.cache/uv/builds-v0/.tmpIFBcmT/lib/python3.11/site-packages/hatchling/builders/plugin/interface.py", line 147, in build
             build_hook.initialize(version, build_data)
           File "/app/hatch_build.py", line 16, in initialize
             raise RuntimeError(
         RuntimeError: NodeJS `npm` is required for building Open Webui but it was not found

         hint: This usually indicates a problem with the package or the build environment.

== Background

The Python dependency management was changed to ensure version
locking/pinning. For that we switched to pyproject.toml as primary list
of dependencies. When it was used for the first time, the build failed
with this error.

Refs: PRODAI-197