chore(notifications): don't use aliases for type enum
To fix typechecker error:

   /app/src/lib/IONOS/components/notifications/NotificationBanner.svelte:23:13
   Error: This comparison appears to be unintentional because the types 'NotificationType.SUCCESS | NotificationType.WARNING' and 'NotificationType.INFO' have no overlap. (ts)
   			<EmojiSad className="text-red-500"/>
   		{:else if $notification.type === NotificationType.INFO}
   			<Touch />

Reason FEEDBACK had the same value as INFO, thus always the first branch
was hit, never the last.

Strictly the types "PWA" or "feedback" should not belong to a
notification data type. This should be refactored in a separate commit.

Refs: PRODAI-380