chore(pyproject): explicitly add "itsdangerous"
To fix the error

     File "/app/backend/open_webui/main.py", line 44, in <module>
       from starlette.middleware.sessions import SessionMiddleware
     File "/usr/local/lib/python3.11/site-packages/starlette/middleware/sessions.py", line 7, in <module>
       import itsdangerous
   ModuleNotFoundError: No module named 'itsdangerous'

This module is loaded by Starlette, which is imported by Open WebUI.

itsdangerous was removed as transitive dependency while removing
colbert-ai, which is no longer used.

Starlette did not explicitly declare "itsdangerous" as dependency [1],
however it's listed as required in the documentation [2].

[1]: https://github.com/Kludex/starlette/blob/0.45.3/requirements.txt
[2]: https://github.com/Kludex/starlette/blob/0.45.3/docs/index.md#dependencies

Refs: PRODAI-418