feat: remove text-to-speech (TTS) engine "transformers"
* To reduce container image size, numbers of dependencies and unused code
* Remove import of dependencies datasets, soundfile, transformers

== Context

* We don't use text-to-speech (TTS) and don't want to run this locally and would prefer support via inference API

== Note on the "transformers" engine

It was broken anyway. When enabled it raised the exception

    RuntimeError: Dataset scripts are no longer supported, but found cmu-arctic-xvectors.py

Refs: PRODAI-418